# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mergePileups <- function(start, end, pileups_pos, pileups_count) {
    .Call(`_MiSiPi_RNA_mergePileups`, start, end, pileups_pos, pileups_count)
}

get_nearby <- function(f_start, f_end, r_start, r_end, max_dist, dfsize) {
    .Call(`_MiSiPi_RNA_get_nearby`, f_start, f_end, r_start, r_end, max_dist, dfsize)
}

getFastas <- function(input_str, start, stop, size) {
    .Call(`_MiSiPi_RNA_getFastas`, input_str, start, stop, size)
}

convertU <- function(input_str, size) {
    .Call(`_MiSiPi_RNA_convertU`, input_str, size)
}

getPileups <- function(dtpos, dtcount, start_r1, end_r1, start_r2, end_r2) {
    .Call(`_MiSiPi_RNA_getPileups`, dtpos, dtcount, start_r1, end_r1, start_r2, end_r2)
}

vectorsToMap <- function(k, v) {
    .Call(`_MiSiPi_RNA_vectorsToMap`, k, v)
}

getPileupsMap <- function(dtpos, dtcount, start_r1, end_r1, start_r2, end_r2, dupe_count_r1, dupe_count_r2) {
    .Call(`_MiSiPi_RNA_getPileupsMap`, dtpos, dtcount, start_r1, end_r1, start_r2, end_r2, dupe_count_r1, dupe_count_r2)
}

group_helix_res <- function(x, y) {
    .Call(`_MiSiPi_RNA_group_helix_res`, x, y)
}

calc_overhangs <- function(r1_start, r1_end, r2_start, r2_width, dupes_present, r1_dupes, r2_dupes) {
    .Call(`_MiSiPi_RNA_calc_overhangs`, r1_start, r1_end, r2_start, r2_width, dupes_present, r1_dupes, r2_dupes)
}

calc_expand_overhangs <- function(r1_start, r1_end, r2_start, r2_width) {
    .Call(`_MiSiPi_RNA_calc_expand_overhangs`, r1_start, r1_end, r2_start, r2_width)
}

proper_overlap <- function(widthx, widthy) {
    .Call(`_MiSiPi_RNA_proper_overlap`, widthx, widthy)
}

overlap_counts <- function(f_start, X_SIZE, r_end, Y_SIZE, overlap) {
    .Call(`_MiSiPi_RNA_overlap_counts`, f_start, X_SIZE, r_end, Y_SIZE, overlap)
}

get_si_overlaps <- function(fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth) {
    .Call(`_MiSiPi_RNA_get_si_overlaps`, fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth)
}

get_phased_dist <- function(startX, endX, startY, endY, dfsize) {
    .Call(`_MiSiPi_RNA_get_phased_dist`, startX, endX, startY, endY, dfsize)
}

make_count_table <- function(fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth) {
    .Call(`_MiSiPi_RNA_make_count_table`, fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth)
}

make_miRNA_count_table_dcroverlap <- function(fdt_start, fdt_end, fwidth, fdupes, rdt_start, rdt_end, rwidth, rdupes) {
    .Call(`_MiSiPi_RNA_make_miRNA_count_table_dcroverlap`, fdt_start, fdt_end, fwidth, fdupes, rdt_start, rdt_end, rwidth, rdupes)
}

make_miRNA_count_table <- function(fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth) {
    .Call(`_MiSiPi_RNA_make_miRNA_count_table`, fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth)
}

map_and_count <- function(fstart, fstart_size, rend, proper_overlap) {
    .Call(`_MiSiPi_RNA_map_and_count`, fstart, fstart_size, rend, proper_overlap)
}

get_pi_overlaps <- function(fdt_start, fdt_end, fwidth, rdt_end, rdt_start, rwidth) {
    .Call(`_MiSiPi_RNA_get_pi_overlaps`, fdt_start, fdt_end, fwidth, rdt_end, rdt_start, rwidth)
}

get_overlap_counts <- function(fdt_start, fdt_end, fwidth, rdt_end, rdt_start, rwidth, check_pi) {
    .Call(`_MiSiPi_RNA_get_overlap_counts`, fdt_start, fdt_end, fwidth, rdt_end, rdt_start, rwidth, check_pi)
}

getLoopPileupsCPP <- function(r1Start, r1Stop, lStart, lStop, r2Start, r2Stop, dt_col_1, dt_col_2, total_count) {
    .Call(`_MiSiPi_RNA_getLoopPileupsCPP`, r1Start, r1Stop, lStart, lStop, r2Start, r2Stop, dt_col_1, dt_col_2, total_count)
}

rep_nonseq_reads <- function(rep_count, rname, start, end, first) {
    .Call(`_MiSiPi_RNA_rep_nonseq_reads`, rep_count, rname, start, end, first)
}

rep_seq_reads <- function(rep_count, rname, start, end, first, seq) {
    .Call(`_MiSiPi_RNA_rep_seq_reads`, rep_count, rname, start, end, first, seq)
}

new_get_si_overlaps <- function(fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth) {
    .Call(`_MiSiPi_RNA_new_get_si_overlaps`, fdt_start, fdt_end, fwidth, rdt_start, rdt_end, rwidth)
}

