# rna_plot
# calls rnafold and rnaplot from viennaRNA and colors the most abundant reads on the structure.
# @param path_to_RNAfold a string, the full path to the RNAfold executable.
# @param path_to_RNAplot a string, the full path to the RNAplot executable.
# @param wkdir a string, the path to the desired working directory.
# @param pos_df a data.frame containing the starts and ends of the abundant reads.
# @param colors a list of two colors for highlighting abundant reads on the structure.
# @param chrom_name a string
# @param reg_start an integer
# @param reg_stop an integer
# @param most_abundant_start an integer
# @param most_abundant_stop an integer
# @param strand a character
# @return nothing

.rna_plot <- function(path_to_RNAfold, path_to_RNAplot, wkdir, pos_df, colors, chrom_name, reg_start, reg_stop, most_abundant_start, most_abundant_stop, strand) {
  syscheck <- Sys.info()["sysname"]

  if (syscheck == "Windows") {
    fold <- system2(
      command = path_to_RNAfold,
      args = paste0(file.path(wkdir, "converted.fasta"), " --outfile=converted.txt"),
      stdout = TRUE,
      wait = TRUE,
      invisible = TRUE
    )
  } else if (syscheck == "Linux" | syscheck == "Darwin") {
    fold <- system(
      command = paste(path_to_RNAfold, file.path(wkdir, "converted.fasta"), "--outfile=converted.txt", sep = " "),
      intern = TRUE
    )
  } else {
    warning("Operating system is not Windows or Linux/Darwin. Returning empty handed.")
    return(NULL)
  }

  # rnafold does not support passing in directories to --outfile at this point
  # moving the file to the correct directory
  file.rename(
    from = file.path("converted.txt"),
    to = file.path(wkdir, "converted.txt")
  )

  # Remove the default plot files generated by RNAfold.exe
  # The -1 to coordinates is to make the filename match the file generated by rnafold/rnaplot when passing in converted
  filename <- paste0(chrom_name, "-", reg_start - 1, "_", reg_stop - 1, "_", "ss.eps")
  #file.remove(file.path(filename))

  # example arguments
  # a <- '--pre="1 15 8 RED omark" test.txt'

  pos1 <- pos_df$r1_start - 1
  pos2 <- pos_df$r1_end - 1
  pos3 <- pos_df$r2_start - 1
  pos4 <- pos_df$r2_end - 1

  final_arg <- paste0(
    "--infile=", wkdir, "/converted.txt ",
    '--pre="',
    pos1, " ", pos2, " ", 8, " ", colors[1], " ", "omark ",
    pos3, " ", pos4, " ", 9, " ", colors[2], " ", 'omark"'
  )

  if (syscheck == "Windows") {
    system2(
      command = path_to_RNAplot,
      args = final_arg,
      stdout = TRUE,
      wait = TRUE,
      invisible = TRUE
    )
  } else if (syscheck == "Linux" | syscheck == "Darwin") {
    system(
      command = paste(path_to_RNAplot, final_arg, sep = " "),
      intern = TRUE
    )
  } else {
    warning("Operating system is not Windows or Linux/Darwin. Returning empty handed.")
    return(NULL)
  }

  # move the ps file to the miRNA directory
  new_filename <- paste0(chrom_name, "-", reg_start - 1, "_", reg_stop - 1, "_", strand, "_", "ss.eps")

  file.rename(
    from = filename,
    to = file.path(wkdir, new_filename)
  )

  file.remove(file.path(wkdir, "converted.txt"))
}
