# rna_plot
# calls rnafold and rnaplot from viennaRNA and colors the most abundant reads on the structure.
# @param path_to_RNAfold a string, the full path to the RNAfold executable.
# @param path_to_RNAplot a string, the full path to the RNAplot executable.
# @param wkdir a string, the path to the desired working directory.
# @param pos_df a data.frame containing the starts and ends of the abundant reads.
# @param colors a list of two colors for highlighting abundant reads on the structure.
# @param prefix either the bed file name or a roi string in the format chr-start_stop
# @param strand a character
# @return nothing

.rna_plot <- function(path_to_RNAfold, path_to_RNAplot, wkdir, pos_df, colors, prefix, strand) {
  syscheck <- Sys.info()["sysname"]
  if (syscheck == "Windows") {
    fold <- system2(
      command = path_to_RNAfold,
      args = paste0(file.path(wkdir, "converted.fasta"), " --outfile=converted.txt"),
      stdout = TRUE,
      wait = TRUE,
      invisible = TRUE
    )
  } else if (syscheck == "Linux" | syscheck == "Darwin") {
    fold <- system(
      command = paste(path_to_RNAfold, file.path(wkdir, "converted.fasta"), "--outfile=converted.txt", sep = " "),
      intern = TRUE
    )
  } else {
    warning("Operating system is not Windows or Linux/Darwin. Returning empty handed.")
    return(NULL)
  }

  # rnafold does not support passing in directories to --outfile at this point
  # moving the file to the correct directory
  file.rename(
    from = file.path("converted.txt"),
    to = file.path(wkdir, "converted.txt")
  )

  # Remove the default plot files generated by RNAfold.exe
  # The -1 to coordinates is to make the filename match the file generated by rnafold/rnaplot when passing in converted
  filename <- paste0(prefix, "_", "ss.eps")
  #file.remove(file.path(filename))

  # example arguments
  # a <- '--pre="1 15 8 RED omark" test.txt'
 
  # In some cases, one of the arms of the most abundant pairs starts or ends outside the locus range
  # In this case, only the arm that is fully inside the region will be colored
  
  if (!is.na(pos_df$r1_start)) {
    pos1 <- pos_df$r1_start
  } else {
    pos1 <- NA
  }
  
  if (!is.na(pos_df$r1_end)) {
    pos2 <- pos_df$r1_end
  } else {
    pos2 <- NA
  }
  
  if (!is.na(pos_df$r2_start)) {
    pos3 <- pos_df$r2_start
  } else {
    pos3 <- NA
  }
  
  if (!is.na(pos_df$r2_end)) {
    pos4 <- pos_df$r2_end
  } else {
    pos4 <- NA
  }
  
  if (!is.na(pos1) & !is.na(pos2) & !is.na(pos3) & !is.na(pos4)) {
    # Color both arms
    final_arg <- paste0(
      "--infile=", wkdir, "/converted.txt ",
      '--pre="',
      pos1, " ", pos2, " ", 8, " ", colors[1], " ", "omark ",
      pos3, " ", pos4, " ", 9, " ", colors[2], " ", 'omark"'
    )
  } else if ((is.na(pos1) | is.na(pos2)) & (is.na(pos3) | is.na(pos4))) {
    # Color nothing
    final_arg <- paste0("--infile=", wkdir, "/converted.txt")
  } else if (is.na(pos1) | is.na(pos2)) {
    # Color second arm
    final_arg <- paste0(
      "--infile=", wkdir, "/converted.txt ",
      '--pre="',
      pos3, " ", pos4, " ", 9, " ", colors[2], " ", 'omark"'
    )
  } else if (is.na(pos3) | is.na(pos4)) {
    # Color first arm
    final_arg <- paste0(
      "--infile=", wkdir, "/converted.txt ",
      '--pre="',
      pos1, " ", pos2, " ", 8, " ", colors[1], " ", "omark "
    )
  }

  if (syscheck == "Windows") {
    system2(
      command = path_to_RNAplot,
      args = final_arg,
      stdout = TRUE,
      wait = TRUE,
      invisible = TRUE
    )
  } else if (syscheck == "Linux" | syscheck == "Darwin") {
    system(
      command = paste(path_to_RNAplot, final_arg, sep = " "),
      intern = TRUE
    )
  } else {
    warning("Operating system is not Windows or Linux/Darwin. Returning empty handed.")
    return(NULL)
  }

  # move the ps file to the miRNA directory
  new_filename <- paste0(prefix, "_", strand, "_", "ss.eps")

  file.rename(
    from = filename,
    to = file.path(wkdir, new_filename)
  )

  file.remove(file.path(wkdir, "converted.txt"))
}
